name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Set up ${{ matrix.compiler }}
      run: sudo apt-get install -y ${{ matrix.compiler }}

    - name: Build project
      run: ./build.sh
